text_type_text = "text"
text_type_bold = "bold"
text_type_italic = "italic"
text_type_code = "code"
text_type_link = "link"
text_type_image = "image"

delimiter_code = "`"
delimiter_bold = "**"
delimiter_italics = "*"
delimiter_headings = "#"
delimiter_links = "[","]"
delimiter_blockquotes = ">"
delimiter_alt_image_text = "![","]"